### ISSUE TITLE
behavior of default=None

### ISSUE THREAD

**Issue by scotthuang1989** [pandas-dev/sklearn-pandas#115] opened 2017-07-25 03:28 UTC
According to the document, if I want do transformation to some of columns in a DataFrame and keep other columns unchanged. I just need set default to None.
eg:
mapper_age_median_standalization_drop_age = DataFrameMapper([
    ('Pclass', sklearn.preprocessing.LabelBinarizer())
 ], input_df=True, df_out=True, default=None)

But the output is very strange, here is the columns name of output dataframe.
Index(['Pclass_1', 'Pclass_2', 'Pclass_3',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_0',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_1',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_2',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_3',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_4',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_5',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_6',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_7',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_8',
       'PassengerId_Name_Sex_Age_SibSp_Parch_Ticket_Fare_Cabin_Embarked_9'],
      dtype='object')

columns name before transform:

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

I know I can workaround this by set column name manually, but this seems like a unexpected behavior to me.

**Comment by scotthuang1989** [comment] 2017-07-25 05:35
after check the sourcecode version: 1.5.0. I found that this behavior is by design:

Here is a partial code of class: DataFrameMapper: in this 2 lines:

        elif isinstance(columns, list):
            name = '_'.join(columns)

columns is a list of name of all unused columns. they are join by _, and then following code will add number to the end of this 'name'.

so I think my question now is why design like this? I am new to data analysis, am I missing something? 

code:

    def get_names(self, columns, transformer, x, alias=None):
        """
        Return verbose names for the transformed columns.

        columns       name (or list of names) of the original column(s)
        transformer   transformer - can be a TransformerPipeline
        x             transformed columns (numpy.ndarray)
        alias         base name to use for the selected columns
        """
        if alias is not None:
            name = alias
        elif isinstance(columns, list):
            name = '_'.join(columns)
        else:
            name = columns
        num_cols = x.shape[1] if len(x.shape) > 1 else 1

**Comment by dukebody** [comment] 2017-07-29 09:11
Thanks a lot @scotthuang1989 for the report! It is really a bug.

The problem is that when we designed the "default" feature we didn't make explicit if the default transformer would be applied to all unselected columns as a whole, or one by one. IMO it makes more sense to apply it to one by one, and that's how we should have done it. Right now it works the other way around, and that's why you get this unexpected behaviour.

To keep backwards compatibility right now and solve the issue you mention I'm going to make the mapper return the names for unselected features unchanged if `default=None`, which makes much more sense.

**Comment by dukebody** [comment] 2017-07-29 09:25
This is fixed in the last master version. We can do a release soon this summer with other changes if necessary.

**Closed** 2017-07-29 09:24 UTC
